### ISSUE TITLE
doesn't display all results

### ISSUE THREAD

**Issue by SarahMouse** [elvismdev/woocommerce-products-by-custom-tax#6]
Hi there,

I am hoping you can help. It is a great plugin, but in my experience, it does not display ALL the products in a taxonomy. Is there any way to get it to do that? At the moment it only displays the first 12 or 14 products. 

Is there some attribute that would allow me to display all the products? Or some other way around this?

Thanks!
Sarah

**Comment by elvismdev** [comment]
qty parameter added https://github.com/elvismdev/woocommerce-products-by-custom-tax/releases/tag/v1.4
