### ISSUE TITLE
order of products by SKU

### ISSUE THREAD

**Issue by SarahMouse** [elvismdev/woocommerce-products-by-custom-tax#7]
Hi Elvis,

Sorry to post this in both the wordpress forum and here on Github, but we are already live and I am hoping that you might be able to help us asap!

We have many products and we love your plugin, however, at the moment, it orders by sku - highest to lowest, and it would be great if we could order by sku - lowest to highest.

Is this possible without too much trouble?

Thanks and kind regards,
Sarah

**Comment by elvismdev** [comment]
I will add another parameter called "order", where you will be able to put ASC or DESC values. Stay in touch for next release update.

**Comment by SarahMouse** [comment]
Hi Elvis,

Thanks so much, that is brilliant. :-) I will look forward to the update.

Cheers,
Sarah

**Comment by elvismdev** [comment]
Order parameter added in https://github.com/elvismdev/woocommerce-products-by-custom-tax/releases/tag/v1.5
